import type { SaleGroup } from '@/data/sale-types';

export const RAW_SALE_DATA: SaleGroup[] = [
 {group:'Phòng', ico:'🛏️', sect:'PHÒNG', cats:[
   {cat:'Hạng phòng — giá mùa hè (đã gồm bữa sáng, đón tàu khung giờ cố định)', rooms:1, items:[
     {id:'r_deluxe', name:'Deluxe (2 khách)', unit:'/phòng/đêm', rates:{wd:1700000,sat:2800000,hol:2800000}, room:1},
     {id:'r_supdlx', name:'Superior Deluxe (2 khách)', unit:'/phòng/đêm', rates:{wd:1900000,sat:3100000,hol:3100000}, room:1},
     {id:'r_bgvuon', name:'Bungalow Vườn (2 khách)', unit:'/phòng/đêm', rates:{wd:2300000,sat:3300000,hol:3300000}, room:1},
     {id:'r_bgho',   name:'Bungalow Hồ (2 khách)',   unit:'/phòng/đêm', rates:{wd:2300000,sat:3300000,hol:3300000}, room:1},
     {id:'r_duplex', name:'Duplex (4 khách)',        unit:'/phòng/đêm', rates:{wd:3400000,sat:5200000,hol:5200000}, room:1},
   ]},
   {cat:'Phụ thu trẻ em & giường phụ (/khách/đêm)', items:[
     {id:'sur_u6_2',  name:'Trẻ dưới 6 tuổi — bé thứ 2 (ngủ cùng)', unit:'/đêm', price:350000, perNight:1, desc:'Bé thứ 1 dưới 6 tuổi: miễn phí (không cần thêm dòng).'},
     {id:'sur_611_s', name:'Trẻ 6–11 tuổi — ngủ cùng',             unit:'/đêm', price:350000, perNight:1},
     {id:'sur_611_b', name:'Trẻ 6–11 tuổi — giường phụ',           unit:'/đêm', price:550000, perNight:1},
     {id:'sur_bed12', name:'Giường phụ (từ 12 tuổi)',              unit:'/đêm', price:750000, perNight:1},
   ]},
 ]},

 {group:'Combo Hè', ico:'🎁', sect:'COMBO', cats:[
   {cat:'Combo Hè Maida (giá /người · áp dụng ngày trong tuần)', items:[
     {id:'cb_deluxe', name:'Combo Deluxe (2 khách/phòng)',          unit:'/người', price:1150000, desc:"Gồm: 1 đêm phòng + 1 bữa sáng + 1 bữa trưa đặc sản (Mango Maida) + chọn 1 trải nghiệm (ngâm chân thảo dược / kayak) + bể bơi vô cực. Áp dụng ngày trong tuần — KHÔNG áp dụng T7 & ngày lễ."},
     {id:'cb_duplex', name:'Combo Duplex (4 khách/phòng)',          unit:'/người', price:1150000, desc:"Gồm: 1 đêm phòng + 1 bữa sáng + 1 bữa trưa đặc sản (Mango Maida) + chọn 1 trải nghiệm (ngâm chân thảo dược / kayak) + bể bơi vô cực. Áp dụng ngày trong tuần — KHÔNG áp dụng T7 & ngày lễ."},
     {id:'cb_supdlx', name:'Combo Superior Deluxe (2 khách/phòng)', unit:'/người', price:1250000, desc:"Gồm: 1 đêm phòng + 1 bữa sáng + 1 bữa trưa đặc sản (Mango Maida) + chọn 1 trải nghiệm (ngâm chân thảo dược / kayak) + bể bơi vô cực. Áp dụng ngày trong tuần — KHÔNG áp dụng T7 & ngày lễ."},
     {id:'cb_bgvuon', name:'Combo Bungalow Vườn (2 khách/phòng)',   unit:'/người', price:1350000, desc:"Gồm: 1 đêm phòng + 1 bữa sáng + 1 bữa trưa đặc sản (Mango Maida) + chọn 1 trải nghiệm (ngâm chân thảo dược / kayak) + bể bơi vô cực. Áp dụng ngày trong tuần — KHÔNG áp dụng T7 & ngày lễ."},
     {id:'cb_bgho',   name:'Combo Bungalow Hồ (2 khách/phòng)',     unit:'/người', price:1450000, desc:"Gồm: 1 đêm phòng + 1 bữa sáng + 1 bữa trưa đặc sản (Mango Maida) + chọn 1 trải nghiệm (ngâm chân thảo dược / kayak) + bể bơi vô cực. Áp dụng ngày trong tuần — KHÔNG áp dụng T7 & ngày lễ."},
     {id:'cb_extra',  name:'Combo-giường phụ',                      unit:'/người', price:1150000, desc:"Gồm: 1 đêm phòng + 1 bữa sáng + 1 bữa trưa đặc sản (Mango Maida) + chọn 1 trải nghiệm (ngâm chân thảo dược / kayak) + bể bơi vô cực. Áp dụng ngày trong tuần — KHÔNG áp dụng T7 & ngày lễ."},
   ]},
 ]},

 {group:'Nhà hàng', ico:'🍽️', sect:'NHÀ HÀNG', cats:[
   {cat:'Set menu (theo suất/người)', items:[
     {id:'set_t1', name:'Set trưa 1', unit:'/người', price:275000, desc:'Nộm hoa chuối tai heo · Cá lăng hấp xì dầu · Nem cá Maida · Rau xào theo mùa · Thịt rang cháy cạnh · Canh cá măng chua · Cơm · Hoa quả'},
     {id:'set_t2', name:'Set trưa 2', unit:'/người', price:275000, desc:'Nộm gà xé phay · Cá diêu hồng hấp xì dầu · Cà tím om nấm · Rau luộc theo mùa · Bò xào ngồng tỏi · Canh tép mùng tơi · Cơm · Hoa quả'},
     {id:'set_t3', name:'Set trưa 3', unit:'/người', price:275000, desc:'Gỏi hoa chuối cá lăng · Gà hấp lá chanh · Cá trắm hấp xì dầu · Củ quả luộc · Thịt lợn kho Maida · Canh thịt nấu chua · Cơm · Hoa quả'},
     {id:'set_o1', name:'Set tối 1', unit:'/người', price:325000, desc:'Nộm gà xé phay · Cá diêu hồng nướng · Nem cá Maida · Thịt nướng lá móc mật · Cà tím om nấm · Rau luộc theo mùa · Canh tép mùng tơi · Cơm · Hoa quả'},
     {id:'set_o2', name:'Set tối 2', unit:'/người', price:325000, desc:'Nộm hoa chuối tai heo · Khoai tây chiên · Nem cá Maida · Cá lăng nướng Maida · Lẩu cá lăng · Hoa quả'},
     {id:'set_o3', name:'Set tối 3', unit:'/người', price:325000, desc:'Nộm hoa chuối tai heo · Gà nướng hạt dổi kèm xôi cẩm · Cá trắm hấp xì dầu · Thịt nướng lá móc mật · Củ quả luộc · Canh thịt nấu chua · Cá sông Đà kho · Cơm · Hoa quả'},
     {id:'set_2_1', name:'Set 2 người – 1', unit:'/người', price:275000, desc:"Thịt lợn nướng lá móc mật · Cá trắm hấp xì dầu · Canh cá măng chua · Cải mèo xào nấm · Cơm trắng · Hoa quả"},
     {id:'set_2_2', name:'Set 2 người – 2', unit:'/người', price:275000, desc:'Gỏi hoa chuối cá lăng · Khoai tây chiên · Lẩu cá lăng · Hoa quả'},
     {id:'set_2_3', name:'Set 2 người – 3', unit:'/người', price:275000, desc:'Cá lăng nướng Maida · Cải mèo luộc chấm trứng · Thịt lợn kho hạt dổi · Canh tép mùng tơi · Cơm · Hoa quả'},
     {id:'set_4_1', name:'Set 4 người – 1', unit:'/người', price:275000, desc:'Nộm hoa chuối tai heo · Thịt lợn nướng lá móc mật · Cải mèo xào nấm · Cá sông Đà kho · Canh cá măng chua · Cơm · Hoa quả'},
     {id:'set_4_2', name:'Set 4 người – 2', unit:'/người', price:275000, desc:'Nộm gà xé phay · Nem cá Maida · Khoai tây chiên · Lẩu cá lăng · Hoa quả'},
     {id:'set_4_3', name:'Set 4 người – 3', unit:'/người', price:275000, desc:'Cá lăng nướng Maida · Cà tím om nấm · Cải mèo luộc chấm trứng · Thịt lợn kho Maida · Canh tép mùng tơi · Cơm · Hoa quả'},
     {id:'set_4_4', name:'Set 4 người – 4', unit:'/người', price:275000, desc:'Gỏi hoa chuối cá lăng · Gà nướng hạt dổi (kèm xôi) · Củ quả luộc · Thịt lợn kho · Canh thịt nấu chua · Cơm · Hoa quả'},
     {id:'set_bbq', name:'Set BBQ (từ 6 suất)', unit:'/người', price:500000, desc:'Nộm hoa chuối tai heo · Gà nướng hạt dổi · Lõi vai bò nướng · Má heo nướng · Cá nướng Tây Bắc · Củ quả luộc · Củ quả nướng · Xôi cẩm · Bánh mì bơ tỏi/mật ong · Hoa quả'},
   ]},
   {cat:'Khai vị / Nộm – Salad', items:[
     {id:'k1',name:'Nộm gà xé phay',unit:'/đĩa',price:165000},
     {id:'k2',name:'Nộm gà ngó sen',unit:'/đĩa',price:175000},
     {id:'k3',name:'Nộm hoa chuối tai heo',unit:'/đĩa',price:165000},
     {id:'k4',name:'Nộm hoa chuối cá lăng',unit:'/đĩa',price:175000},
     {id:'k5',name:'Gỏi cá diêu hồng',unit:'/đĩa',price:395000},
     {id:'k6',name:'Salad hoa quả',unit:'/đĩa',price:115000},
     {id:'k7',name:'Salad rau củ',unit:'/đĩa',price:85000},
   ]},
   {cat:'Cá', items:[
     {id:'f1',name:'Cá lăng nướng Mai Đà',unit:'/phần',price:365000},
     {id:'f2',name:'Cá lăng hấp xì dầu',unit:'/phần',price:365000},
     {id:'f3',name:'Cá diêu hồng hấp xì dầu',unit:'/phần',price:445000},
     {id:'f4',name:'Cá diêu hồng nướng Mai Đà',unit:'/phần',price:455000},
     {id:'f5',name:'Cá diêu hồng chiên xù',unit:'/phần',price:195000},
     {id:'f6',name:'Cá trắm hấp xì dầu',unit:'/phần',price:250000},
     {id:'f7',name:'Cá trê nướng Mai Đà',unit:'/phần',price:475000},
     {id:'f8',name:'Chả cá Mai Đà',unit:'/phần',price:400000},
     {id:'f9',name:'Cá lăng xào dứa',unit:'/phần',price:355000},
     {id:'f10',name:'Cá lăng om chuối đậu',unit:'/phần',price:375000},
     {id:'f11',name:'Nem cá Mai Đà (cái)',unit:'/cái',price:25000},
     {id:'f12',name:'Nem cá Mai Đà (đĩa 10 cái)',unit:'/đĩa',price:250000},
     {id:'f13',name:'Cá Sông Đà chiên lá lốt',unit:'/phần',price:165000},
   ]},
   {cat:'Gà / Bò / Lợn', items:[
     {id:'m1',name:'Gà hấp lá chanh (1/2 con)',unit:'/phần',price:425000},
     {id:'m2',name:'Gà rang gừng (1/2 con)',unit:'/phần',price:435000},
     {id:'m3',name:'Gà nướng hạt dổi (1/2 con)',unit:'/phần',price:465000},
     {id:'m4',name:'Gà chiên mắm (1/2 con)',unit:'/phần',price:450000},
     {id:'m5',name:'Gà nấu măng chua',unit:'/phần',price:435000},
     {id:'m6',name:'Bò bít tết',unit:'/phần',price:320000},
     {id:'m7',name:'Lõi vai bò nướng',unit:'/phần',price:455000},
     {id:'m8',name:'Mỳ Ý sốt bò bằm',unit:'/phần',price:280000},
     {id:'m9',name:'Má heo nướng Mai Đà',unit:'/phần',price:275000},
     {id:'m10',name:'Dải heo chao lá móc mật',unit:'/phần',price:255000},
     {id:'m11',name:'Thịt lợn nướng lá móc mật',unit:'/phần',price:255000},
     {id:'m12',name:'Thăn lợn chiên xù',unit:'/phần',price:210000},
     {id:'m13',name:'Cánh gà chiên mắm',unit:'/phần',price:195000},
     {id:'m14',name:'Khoai tây chiên',unit:'/phần',price:95000},
     {id:'m15',name:'Xôi nếp cẩm',unit:'/phần',price:65000},
   ]},
   {cat:'Rau / Trứng / Cơm chay', items:[
     {id:'v1',name:'Cải mèo luộc chấm trứng',unit:'/phần',price:85000},
     {id:'v2',name:'Cải mèo xào nấm',unit:'/phần',price:95000},
     {id:'v3',name:'Củ quả luộc',unit:'/phần',price:90000},
     {id:'v4',name:'Bắp cải luộc chấm trứng',unit:'/phần',price:65000},
     {id:'v5',name:'Rau muống luộc',unit:'/phần',price:55000},
     {id:'v6',name:'Rau muống xào giòn',unit:'/phần',price:75000},
     {id:'v7',name:'Cải chíp luộc sốt nấm',unit:'/phần',price:95000},
     {id:'v8',name:'Cải chip xào nấm',unit:'/phần',price:95000},
     {id:'v9',name:'Măng tươi xào (theo mùa)',unit:'/phần',price:105000},
     {id:'v10',name:'Cà tím om nấm',unit:'/phần',price:160000},
     {id:'v11',name:'Súp lơ xào nấm',unit:'/phần',price:115000},
     {id:'v12',name:'Đậu cô ve luộc gừng',unit:'/phần',price:60000},
     {id:'v13',name:'Trứng hấp miến nấm',unit:'/phần',price:185000},
     {id:'v14',name:'Trứng đúc nấm sốt phô mai',unit:'/phần',price:185000},
     {id:'v15',name:'Trứng tráng',unit:'/phần',price:65000},
     {id:'v16',name:'Canh nấm lá lốt',unit:'/phần',price:95000},
     {id:'v17',name:'Canh rau cải gừng',unit:'/phần',price:60000},
     {id:'v18',name:'Cơm chả lá lốt cuộn đậu nấm',unit:'/phần',price:185000},
     {id:'v19',name:'Cơm nấm xào rau củ',unit:'/phần',price:155000},
     {id:'v20',name:'Mỳ Ý chay sốt cà chua',unit:'/phần',price:220000},
   ]},
   {cat:'Món phụ / Canh / Cơm', items:[
     {id:'s1',name:'Cá kho Mai Đà',unit:'/phần',price:255000},
     {id:'s2',name:'Thịt kho Mai Đà',unit:'/phần',price:185000},
     {id:'s3',name:'Thịt rang cháy cạnh',unit:'/phần',price:185000},
     {id:'s4',name:'Thịt ba chỉ luộc',unit:'/phần',price:165000},
     {id:'s5',name:'Tôm sông rang lá chanh',unit:'/phần',price:265000},
     {id:'s6',name:'Tôm sông rang thịt',unit:'/phần',price:265000},
     {id:'s7',name:'Măng treo xào bò',unit:'/phần',price:250000},
     {id:'s8',name:'Ngồng tỏi xào bò',unit:'/phần',price:250000},
     {id:'s9',name:'Trứng đúc thịt',unit:'/phần',price:115000},
     {id:'s10',name:'Canh sườn chua dọc mùng',unit:'/phần',price:175000},
     {id:'s11',name:'Canh cá măng chua',unit:'/phần',price:165000},
     {id:'s12',name:'Canh tép mùng tơi',unit:'/phần',price:145000},
     {id:'s13',name:'Canh sườn măng chua',unit:'/phần',price:175000},
     {id:'s14',name:'Canh thịt nấu chua',unit:'/phần',price:135000},
     {id:'s15',name:'Canh cải thịt băm',unit:'/phần',price:125000},
     {id:'s16',name:'Cơm rang thập cẩm',unit:'/phần',price:125000},
     {id:'s17',name:'Mỳ xào bò',unit:'/phần',price:135000},
     {id:'s18',name:'Nồi cháo gà (1/2 con, 4 người)',unit:'/nồi',price:500000},
     {id:'s19',name:'Cháo thịt băm (bát)',unit:'/bát',price:60000},
     {id:'s20',name:'Cơm trắng',unit:'/bát',price:30000},
   ]},
   {cat:'Lẩu', items:[
     {id:'l1',name:'Lẩu cá lăng',unit:'/nồi',price:685000},
     {id:'l2',name:'Lẩu gà dấm bỗng',unit:'/nồi',price:665000},
     {id:'l3',name:'Cá lăng phile (nhúng lẩu)',unit:'/phần',price:275000},
     {id:'l4',name:'Bò nhúng lẩu',unit:'/phần',price:195000},
     {id:'l5',name:'Gà thả lẩu (1/2 con)',unit:'/phần',price:375000},
     {id:'l6',name:'Nấm kim châm',unit:'/phần',price:65000},
     {id:'l7',name:'Rau cải xanh',unit:'/phần',price:45000},
     {id:'l8',name:'Măng lẩu',unit:'/phần',price:75000},
     {id:'l9',name:'Váng đậu',unit:'/phần',price:40000},
     {id:'l10',name:'Rau cải mèo',unit:'/phần',price:55000},
     {id:'l11',name:'Rau cải thảo',unit:'/phần',price:55000},
     {id:'l12',name:'Rau tổng hợp',unit:'/phần',price:115000},
     {id:'l13',name:'Mì tôm',unit:'/gói',price:30000},
     {id:'l14',name:'Bánh đa',unit:'/phần',price:35000},
     {id:'l15',name:'Bún',unit:'/phần',price:35000},
   ]},
   {cat:'Tráng miệng', items:[
     {id:'d1',name:'Hoa quả tráng miệng',unit:'/đĩa',price:50000},
     {id:'d2',name:'Panna cotta',unit:'/phần',price:20000},
   ]},
   {cat:'Đồ uống — Nước ép & Trà', items:[
     {id:'b1',name:'Nước cam ép',unit:'/ly',price:60000},
     {id:'b2',name:'Nước chanh tươi',unit:'/ly',price:40000},
     {id:'b3',name:'Nước chanh leo',unit:'/ly',price:50000},
     {id:'b4',name:'Cam dứa ép',unit:'/ly',price:65000},
     {id:'b5',name:'Nước mơ',unit:'/ly',price:50000},
     {id:'b6',name:'Dưa hấu ép',unit:'/ly',price:50000},
     {id:'b7',name:'Cam cà rốt ép',unit:'/ly',price:70000},
     {id:'b8',name:'Dứa ép',unit:'/ly',price:55000},
     {id:'b9',name:'Trà hoa quả nha đam',unit:'/ly',price:60000},
     {id:'b10',name:'Trà hoa cúc táo đỏ',unit:'/ly',price:60000},
     {id:'b11',name:'Trà lá nếp nha đam',unit:'/ly',price:60000},
     {id:'b12',name:'Trà cam quế (ấm)',unit:'/ly',price:60000},
     {id:'b13',name:'Trà gừng mật ong',unit:'/ly',price:50000},
     {id:'b14',name:'Trà quất mật ong',unit:'/ly',price:50000},
     {id:'b15',name:'Trà mạn (ấm)',unit:'/ấm',price:70000},
     {id:'b16',name:'Trà cam quế (lạnh)',unit:'/ly',price:60000},
     {id:'b17',name:'Trà gạo lứt (bình)',unit:'/bình',price:80000},
     {id:'b18',name:'Sprite chanh leo',unit:'/ly',price:60000},
     {id:'b19',name:'Trà sâm dứa (bình)',unit:'/bình',price:60000},
     {id:'b20',name:'Soda xí muội',unit:'/ly',price:60000},
     {id:'b21',name:'Trà sâm dứa (cốc)',unit:'/cốc',price:15000},
   ]},
   {cat:'Đồ uống — Nước ngọt / Bia / Rượu', items:[
     {id:'g1',name:'Lavie',unit:'/chai',price:25000},
     {id:'g2',name:'Bia Hà Nội',unit:'/lon',price:35000},
     {id:'g3',name:'Bia Heineken',unit:'/lon',price:45000},
     {id:'g4',name:'Coca Cola',unit:'/lon',price:35000},
     {id:'g5',name:'Bia Tiger Bạc',unit:'/lon',price:50000},
     {id:'g6',name:'Soda chanh',unit:'/ly',price:35000},
     {id:'g7',name:'Rượu táo mèo',unit:'/bình',price:300000},
     {id:'g8',name:'Sprite',unit:'/lon',price:35000},
     {id:'g9',name:'Rượu mơ',unit:'/bình',price:300000},
   ]},
   {cat:'Đồ uống — Cà phê / Cocktail / Sữa', items:[
     {id:'c1',name:'Cà phê đen',unit:'/ly',price:50000},
     {id:'c2',name:'Cà phê nâu',unit:'/ly',price:55000},
     {id:'c3',name:'Bạc xỉu',unit:'/ly',price:60000},
     {id:'c4',name:'Cà phê muối',unit:'/ly',price:55000},
     {id:'c5',name:'Classic Mojito',unit:'/ly',price:115000},
     {id:'c6',name:'Passion Mojito',unit:'/ly',price:130000},
     {id:'c7',name:'Cocktail homemade',unit:'/ly',price:115000},
     {id:'c8',name:'Sữa chua đánh đá',unit:'/ly',price:55000},
     {id:'c9',name:'Sữa chua nha đam',unit:'/ly',price:60000},
     {id:'c10',name:'Sữa chua chanh leo',unit:'/ly',price:60000},
     {id:'c11',name:'Sữa tươi',unit:'/ly',price:30000},
   ]},
   {cat:'Thêm món / đồ uống tự do', custom:1, sect:'NHÀ HÀNG', items:[]},
 ]},

 {group:'Dịch vụ', ico:'🌿', sect:'DỊCH VỤ', cats:[
   {cat:'Trải nghiệm trên hồ', items:[
     {id:'e1',name:'Ván hơi SUP (1 người)',unit:'/lượt',price:150000},
     {id:'e2',name:'Kayak (2 người)',unit:'/lượt',price:250000},
     {id:'e3',name:'Tàu đi chơi hồ (1–17 người, gần Maida)',unit:'/giờ',price:600000,desc:'Trên 18 người / đi lễ / du ngoạn hồ: đặt trước.'},
   ]},
   {cat:'Tắm lá thuốc người Dao', items:[
     {id:'e4',name:'Ngâm chân lá thuốc',unit:'/chậu',price:120000},
     {id:'e5',name:'Bồn ngâm tắm lá thuốc',unit:'/bồn',price:300000},
   ]},
   {cat:'Văn nghệ & âm thanh', items:[
     {id:'e6',name:'Văn nghệ dân tộc',unit:'/show',price:3500000},
     {id:'e7',name:'Âm ly, loa, mic',unit:'/lượt',price:2000000},
   ]},
   {cat:'Địa điểm & Hội nghị', items:[
     {id:'p1',name:'Thuê địa điểm tổ chức sự kiện',unit:'/ngày',price:5000000},
     {id:'p2',name:'Phòng đa năng (4 tiếng)',unit:'/lượt',price:5000000},
     {id:'p3',name:'Phí phục vụ ăn tại phòng đa năng',unit:'/bữa',price:1000000},
     {id:'p4',name:'Phí phục vụ đồ uống',unit:'/mâm',price:500000},
   ]},
   {cat:'Bếp nướng & Teabreak', items:[
     {id:'q1',name:'Set bếp nướng ngô khoai (5–8 người)',unit:'/set',price:500000},
     {id:'q2',name:'Set bếp nướng ngô khoai (15–20 người)',unit:'/set',price:1000000},
     {id:'q3',name:'Teabreak (15–20 người)',unit:'/set',price:2500000},
     {id:'q4',name:'Teabreak (30–40 người)',unit:'/set',price:3500000},
   ]},
 ]},

 {group:'Vận chuyển', ico:'🚐', sect:'VẬN CHUYỂN', cats:[
   {cat:'Tàu đưa đón Ngòi Hoa – Maida', items:[
     {id:'t1',name:'Tàu 1–17 người',unit:'/lượt',price:550000,desc:'Đón/trả ngoài khung giờ cố định.'},
     {id:'t2',name:'Tàu 1–17 người (sau 18h00)',unit:'/lượt',price:750000},
     {id:'t3',name:'Tàu 18–35 người',unit:'/lượt',price:2000000},
     {id:'t4',name:'Tàu 31–60 người (đặt trước)',unit:'',price:0,note:'Đặt trước',askPrice:1},
   ]},
   {cat:'Thuê xe ô tô (giá theo thoả thuận nhà xe)', items:[
     {id:'x_car',name:'Thuê xe ô tô Hà Nội → Ngòi Hoa',unit:'/chuyến',price:0,askPrice:1,note:'Không có giá cố định — Sale điền giá đã chốt với nhà xe.'},
   ]},
 ]},
];
